### ISSUE TITLE
add custom font 

### ISSUE THREAD

**Issue by ManishSharmaApporio** [UrbanChrisy/rn-snackbar#5]
Hi Team,
i m trying to add custom font to SnackBar but it didn't work for me.Please help me out for the same.
SnackBar.show(text, {
    style: { fontFamily: MontserratMedium },
    isStatic: false,
    duration: duration,
    position: "top",
    backgroundColor: color
  });

"react-native": "^0.59.6",
 "rn-snackbar": "^1.0.6"

**Comment by UrbanChrisy** [comment]
Sorry about not replaying, I no longer maintain this project anymore. But feel free to submit a pr.
